version: '3'
services:
  db:
    restart: always
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pwd
    volumes:
      - "dpl_db:/var/lib/postgresql/data"
    expose:
      - 5432
    ports:
      - 5433:5432
    networks:
      - dpl_tier
  web:
    restart: always
    build: .
    depends_on:
      - db

    command: python manage.py runserver 0.0.0.0:8000

    environment:
      - DJANGO_COLLECT_STATIC=off
      - DJANGO_MANAGEPY_MIGRATE=on
    links:
      - db:postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
    - dpl_tier
volumes:
  dpl_db:
    driver: local
  static_volume:
    driver: local
networks:
  dpl_tier:
    driver: bridge